/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:54ebb509-d63d-4431-8a2d-16e5aa9c1906",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FpO2136FC",
    "aws_user_pools_web_client_id": "shjp9rfero12kllc7msnlfe7u",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "usublease686cd1e50d924eaa9ce4cb7a0d2375fb0cf77-venv",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
